# Run all tests on PMEM.
#
# This workflow is run on 'self-hosted' runners.
name: PMEM tests part 4

on:
  workflow_dispatch:
  schedule:
    # run this job at 18:00 UTC every Sunday
    - cron:  '0 18 * * 0'

permissions: {}

jobs:
  # Test the default build with force-enabled Valgrind tooling for thread error
  # detection.
  Thread:
    uses: ./.github/workflows/pmem_test_matrix.yml
    with:
      force_enable: '["drd"]'
      valgrind: 1
      # 24h = 1440m (arbitrarily picked in hope it will be enough).
      timeout_minutes: 1440
